// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuM3lvHRbk2XkciuLGxbJyU7klpimbqhc',
    appId: '1:407240363812:web:f7db202919e3935cf7adb1',
    messagingSenderId: '407240363812',
    projectId: 'counter-f7572',
    authDomain: 'counter-f7572.firebaseapp.com',
    storageBucket: 'counter-f7572.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU23fB6-591nInJmpzejPMUabVC_VnZjg',
    appId: '1:407240363812:android:a21d871baff846f0f7adb1',
    messagingSenderId: '407240363812',
    projectId: 'counter-f7572',
    storageBucket: 'counter-f7572.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXQhTei9bUKzPwIiTc1K09och-5mya56U',
    appId: '1:407240363812:ios:641598648dba0994f7adb1',
    messagingSenderId: '407240363812',
    projectId: 'counter-f7572',
    storageBucket: 'counter-f7572.appspot.com',
    iosBundleId: 'com.example.counterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXQhTei9bUKzPwIiTc1K09och-5mya56U',
    appId: '1:407240363812:ios:641598648dba0994f7adb1',
    messagingSenderId: '407240363812',
    projectId: 'counter-f7572',
    storageBucket: 'counter-f7572.appspot.com',
    iosBundleId: 'com.example.counterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuM3lvHRbk2XkciuLGxbJyU7klpimbqhc',
    appId: '1:407240363812:web:5ebe55f847fe442cf7adb1',
    messagingSenderId: '407240363812',
    projectId: 'counter-f7572',
    authDomain: 'counter-f7572.firebaseapp.com',
    storageBucket: 'counter-f7572.appspot.com',
  );
}
